### ISSUE TITLE
TOI ability?

### ISSUE THREAD

**Issue by TonMachielsen** [impinj/itemsense-viztool-js#17]
Can we have the ability to load TOI files and color tags just like in Itemtest?

**Comment by ralemy** [comment]
We already have. That is what the classification tab is for. You can upload csv files for TOI and add colors and images for items. 
Let me know if you were interested in more details. 
Cheers
Reza

**Comment by TonMachielsen** [comment]
Ok, so you call this Classification now. Understood. BTW, I imported a POI file (after changing the extension from .poi to .csv) but the Classification tab is shown as locked in my instance (pull from 20th of May). Do i need to update the code?

**Comment by ralemy** [comment]
you should not need to update the code. The format for csv for
Classification tab is a little different from itemtest poi files. Gary is
making a video to show it. in the meantime, contact me directly to set up a
video conference and I'll show you how to use it.
Once you get it running we can use your feedback to make it better.

Cheers,
Reza
