### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by KyubiEdu** [impinj/itemsense-viztool-js#21]
I'm trying to install on 

`node -v
v10.16.0
`
`npm -v
6.9.0
`
On the terminal I get error:

`In file included from ../../nan/nan.h:192:0,
                 from ../src/binding.cpp:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
`
On the log this is the end:

`18778 verbose stack Error: node-sass@3.13.1 postinstall: `node scripts/build.js`
18778 verbose stack Exit status 1
18778 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
18778 verbose stack     at EventEmitter.emit (events.js:198:13)
18778 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18778 verbose stack     at ChildProcess.emit (events.js:198:13)
18778 verbose stack     at maybeClose (internal/child_process.js:982:16)
18778 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
18779 verbose pkgid node-sass@3.13.1
18780 verbose cwd /home/kyubi/itemsense-viztool-js
18781 verbose Linux 4.18.0-22-generic
18782 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
18783 verbose node v10.16.0
18784 verbose npm  v6.9.0
18785 error code ELIFECYCLE
18786 error errno 1
18787 error node-sass@3.13.1 postinstall: `node scripts/build.js`
18787 error Exit status 1
18788 error Failed at the node-sass@3.13.1 postinstall script.
18788 error This is probably not a problem with npm. There is likely additional logging output above.
18789 verbose exit [ 1, true ]
`

Any idea?

**Comment by JaredKnapp** [comment]
Possibly related to this? https://github.com/nodejs/nan/issues/763

I'm guessing that npm is too current, and needs to be downgraded for this rev. We are currently planning an upgrade of this project, but we're not there yet.

**Comment by KyubiEdu** [comment]
Thanks, I just Downgrade to nodejs 8 and now is working.
